/* =========================================================
   Dashboard Work Hub

   จุดประสงค์
   - /admin/dashboard เป็นทางเข้าหลักเมื่อ Sidebar ถูกลด/นำออก
   - "งานหลักตาม Role" ใช้ Role เพื่อจัดลำดับงานที่ควรเห็นก่อน
   - "งานที่ใช้เป็นประจำทั้งหมด" แสดงทุกงานปฏิบัติการที่ User มี Permission
   - "ตั้งค่าพื้นฐาน HRMS" เก็บ Master/Setup และเปิด-ปิดได้
   - Permission เป็นตัวตัดสินสุดท้ายว่าปุ่มใดแสดงและกดได้
   - Route ในไฟล์นี้ยึดตาม MenuHRMS เพื่อไม่ให้เมนูหายเมื่อเอา Sidebar ออก
========================================================= */

export const DAILY_WORK_GROUPS = [
  {
    key: "daily-1",
    order: 1,
    title: "องค์กรและตำแหน่ง",
    subtitle: "งานโครงสร้างองค์กร การครองตำแหน่ง และผังองค์กร",
    icon: "ApartmentOutlined",
    items: [
      {
        key: "/admin/divisional-structures",
        label: "โครงสร้างองค์กรตามแผนก",
        description: "ดูและจัดการโครงสร้างองค์กรตามแผนก",
        href: "/admin/divisional-structures",
        permission: "ems.org_structure.view",
        icon: "ApartmentOutlined",
      },
      {
        key: "/admin/employee-position-assignments",
        label: "การครองตำแหน่งองค์กร",
        description: "ตรวจและจัดการว่าใครครอง Position Slot ใดอยู่",
        href: "/admin/employee-position-assignments",
        permission: "ems.org_structure.view",
        icon: "ApartmentOutlined",
      },
      {
        key: "/admin/org-chart",
        label: "ผังโครงสร้างองค์กร (Org Chart)",
        description: "ดูผังองค์กรและสายบังคับบัญชา",
        href: "/admin/org-chart",
        permission: "ems.org_chart.view",
        icon: "ApartmentOutlined",
      },
    ],
  },
  {
    key: "daily-2",
    order: 2,
    title: "ทักษะและสมรรถนะ",
    subtitle: "ดูแลทักษะของพนักงานรายบุคคล",
    icon: "TeamOutlined",
    items: [
      {
        key: "/admin/employee-skills",
        label: "ทักษะรายบุคคล",
        description: "เปิดหน้า ทักษะรายบุคคล",
        href: "/admin/employee-skills",
        permission: "ems.employee_skills.view",
        icon: "TeamOutlined",
      },
    ],
  },
  {
    key: "daily-3",
    order: 3,
    title: "นโยบายและแผน",
    subtitle: "งานนโยบาย แผน HR และ Compliance ที่ต้องทบทวนตามรอบ",
    icon: "FileTextOutlined",
    items: [
      {
        key: "/admin/hr-policies",
        label: "นโยบายบริษัท",
        description: "เปิดหน้า นโยบายบริษัท",
        href: "/admin/hr-policies",
        permission: "policy.hr_policies.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/compensation-policies",
        label: "นโยบายค่าตอบแทน (Compensation Policy)",
        description: "เปิดหน้า นโยบายค่าตอบแทน (Compensation Policy)",
        href: "/admin/compensation-policies",
        permission: "policy.compensation_policies.view",
        icon: "DollarOutlined",
      },
      {
        key: "/admin/employee-handbooks",
        label: "ระเบียบข้อบังคับพนักงาน (Employee Handbook)",
        description: "เปิดหน้า ระเบียบข้อบังคับพนักงาน (Employee Handbook)",
        href: "/admin/employee-handbooks",
        permission: "policy.employee_handbooks.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/compliance-policies",
        label: "นโยบายการปฏิบัติตามกฎหมาย / PDPA",
        description: "เปิดหน้า นโยบายการปฏิบัติตามกฎหมาย / PDPA",
        href: "/admin/compliance-policies",
        permission: "policy.compliance_policies.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/hr-strategic-plans",
        label: "แผนกลยุทธ์ HR",
        description: "เปิดหน้า แผนกลยุทธ์ HR",
        href: "/admin/hr-strategic-plans",
        permission: "policy.strategic_plans.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/policy-versions",
        label: "ประวัติการแก้ไขนโยบาย (Version History)",
        description: "เปิดหน้า ประวัติการแก้ไขนโยบาย (Version History)",
        href: "/admin/policy-versions",
        permission: "policy.policy_versions.view",
        icon: "FileTextOutlined",
      },
    ],
  },
  {
    key: "daily-4",
    order: 4,
    title: "สวัสดิการ",
    subtitle: "สิทธิ์สวัสดิการ คำขอ และการอนุมัติ",
    icon: "CheckCircleOutlined",
    items: [
      {
        key: "/admin/benefit-entitlements",
        label: "สิทธิ์สวัสดิการพนักงาน (Entitlements)",
        description: "เปิดหน้า สิทธิ์สวัสดิการพนักงาน (Entitlements)",
        href: "/admin/benefit-entitlements",
        permission: "benefits.entitlements.view",
        icon: "SolutionOutlined",
      },
      {
        key: "/admin/benefit-approvals",
        label: "คำขอเบิกสวัสดิการ / อนุมัติ",
        description: "เปิดหน้า คำขอเบิกสวัสดิการ / อนุมัติ",
        href: "/admin/benefit-approvals",
        permission: "benefits.approvals.view",
        icon: "CheckCircleOutlined",
      },
      {
        key: "/admin/benefit-audit-logs",
        label: "Audit Log สวัสดิการ",
        description: "เปิดหน้า Audit Log สวัสดิการ",
        href: "/admin/benefit-audit-logs",
        permission: "benefits.audit_logs.view",
        icon: "AuditOutlined",
      },
    ],
  },
  {
    key: "daily-5",
    order: 5,
    title: "เงินเดือนและค่าตอบแทน",
    subtitle: "ค่าตอบแทน งวดเงินเดือน และการประมวลผล",
    icon: "DollarOutlined",
    items: [
      {
        key: "/admin/employee-compensations",
        label: "ค่าตอบแทนพนักงาน",
        description: "ตรวจและจัดการ Base Salary, Salary Band และค่าตอบแทนของพนักงาน",
        href: "/admin/employee-compensations",
        permission: "ems.employee_compensations.view",
        icon: "DollarOutlined",
      },
      {
        key: "/admin/payroll-periods",
        label: "งวดเงินเดือน",
        description: "เปิด/ปิดและตรวจงวดเงินเดือน",
        href: "/admin/payroll-periods",
        permission: "ems.payroll_periods.view",
        icon: "CalendarOutlined",
      },
      {
        key: "/admin/payroll-runs",
        label: "ประมวลผลเงินเดือน",
        description: "ตรวจและประมวลผลงวดเงินเดือน",
        href: "/admin/payroll-runs",
        permission: "ems.payroll_runs.view",
        icon: "WalletOutlined",
      },
    ],
  },
  {
    key: "daily-6",
    order: 6,
    title: "ภาษีและประกันสังคม",
    subtitle: "ข้อมูลภาษีและประกันสังคมของพนักงาน",
    icon: "SafetyCertificateOutlined",
    items: [
      {
        key: "/admin/employee-statutory-profiles",
        label: "ภาษี / ประกันสังคมพนักงาน",
        description: "ตรวจและจัดการข้อมูล ภ.ง.ด. และประกันสังคม",
        href: "/admin/employee-statutory-profiles",
        permission: "ems.employee_statutory_profiles.view",
        icon: "IdcardOutlined",
      },
    ],
  },
  {
    key: "daily-7",
    order: 7,
    title: "บัญชีธนาคารพนักงาน",
    subtitle: "บัญชีรับเงินเดือนของพนักงาน",
    icon: "BankOutlined",
    items: [
      {
        key: "/admin/employee-bank-accounts",
        label: "บัญชีธนาคารพนักงาน",
        description: "ตรวจและจัดการบัญชีรับเงินเดือนของพนักงาน",
        href: "/admin/employee-bank-accounts",
        permission: "ems.employee_bank_accounts.view",
        icon: "BankOutlined",
      },
    ],
  },
  {
    key: "daily-8",
    order: 8,
    title: "พนักงาน",
    subtitle: "ทะเบียนพนักงานและรายงาน",
    icon: "IdcardOutlined",
    items: [
      {
        key: "/admin/employees",
        label: "พนักงาน",
        description: "ค้นหา เพิ่ม แก้ไข และตรวจข้อมูลพนักงาน",
        href: "/admin/employees",
        permission: "ems.employees.view",
        icon: "IdcardOutlined",
      },
      {
        key: "/admin/employee-reports",
        label: "รายงานพนักงาน",
        description: "เปิดหน้า รายงานพนักงาน",
        href: "/admin/employee-reports",
        permission: "ems.employee_reports.view",
        icon: "BarChartOutlined",
      },
    ],
  },
  {
    key: "daily-9",
    order: 9,
    title: "สรรหาและ Onboarding",
    subtitle: "ตั้งแต่ขอเปิดอัตรา ผู้สมัคร สัมภาษณ์ Offer ถึง Onboarding",
    icon: "TeamOutlined",
    items: [
      {
        key: "/admin/manpower-requisitions",
        label: "ใบขอเปิดอัตรา",
        description: "เปิดหน้า ใบขอเปิดอัตรา",
        href: "/admin/manpower-requisitions",
        permission: "ems.manpower_requisitions.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/job-postings",
        label: "ประกาศรับสมัครงาน",
        description: "เปิดหน้า ประกาศรับสมัครงาน",
        href: "/admin/job-postings",
        permission: "ems.job_postings.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/applicants",
        label: "ผู้สมัครงาน",
        description: "เปิดหน้า ผู้สมัครงาน",
        href: "/admin/applicants",
        permission: "ems.applicants.view",
        icon: "SolutionOutlined",
      },
      {
        key: "/admin/interviews",
        label: "นัดสัมภาษณ์",
        description: "เปิดหน้า นัดสัมภาษณ์",
        href: "/admin/interviews",
        permission: "ems.interviews.view",
        icon: "CalendarOutlined",
      },
      {
        key: "/admin/job-offers",
        label: "ใบเสนอค่าจ้าง",
        description: "เปิดหน้า ใบเสนอค่าจ้าง",
        href: "/admin/job-offers",
        permission: "ems.job_offers.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/onboarding-checklists",
        label: "Onboarding Checklist",
        description: "เปิดหน้า Onboarding Checklist",
        href: "/admin/onboarding-checklists",
        permission: "ems.onboarding_checklists.view",
        icon: "TeamOutlined",
      },
    ],
  },
  {
    key: "daily-10",
    order: 10,
    title: "เวลาเข้างาน / OT / ลา",
    subtitle: "ตารางทำงาน เวลาเข้าออก สิทธิ์ลา และคำขอลา",
    icon: "ClockCircleOutlined",
    items: [
      {
        key: "/admin/work-schedules",
        label: "ตารางเข้างาน",
        description: "เปิดหน้า ตารางเข้างาน",
        href: "/admin/work-schedules",
        permission: "ems.work_schedules.view",
        icon: "CalendarOutlined",
      },
      {
        key: "/admin/attendance-records",
        label: "บันทึกเวลาเข้า-ออกงาน",
        description: "ตรวจข้อมูลเวลาเข้า-ออกงาน",
        href: "/admin/attendance-records",
        permission: "ems.attendance_records.view",
        icon: "ClockCircleOutlined",
      },
      {
        key: "/admin/leave-entitlements",
        label: "โควตาวันลา",
        description: "เปิดหน้า โควตาวันลา",
        href: "/admin/leave-entitlements",
        permission: "ems.leave_entitlements.view",
        icon: "ClockCircleOutlined",
      },
      {
        key: "/admin/leave-requests",
        label: "คำขอลา",
        description: "ติดตามคำขอลาและสถานะการอนุมัติ",
        href: "/admin/leave-requests",
        permission: "ems.leave_requests.view",
        icon: "ClockCircleOutlined",
      },
    ],
  },
  {
    key: "daily-11",
    order: 11,
    title: "สุขภาพและความปลอดภัย",
    subtitle: "อุบัติเหตุ ตรวจสุขภาพ และอบรมความปลอดภัย",
    icon: "SafetyCertificateOutlined",
    items: [
      {
        key: "/admin/incident-records",
        label: "บันทึกอุบัติเหตุ",
        description: "เปิดหน้า บันทึกอุบัติเหตุ",
        href: "/admin/incident-records",
        permission: "ehs.incidents.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/health-checkups",
        label: "ตรวจสุขภาพประจำปี",
        description: "เปิดหน้า ตรวจสุขภาพประจำปี",
        href: "/admin/health-checkups",
        permission: "ehs.health_checkups.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/safety-trainings",
        label: "อบรมความปลอดภัย",
        description: "เปิดหน้า อบรมความปลอดภัย",
        href: "/admin/safety-trainings",
        permission: "ehs.safety_trainings.view",
        icon: "SafetyCertificateOutlined",
      },
    ],
  },
  {
    key: "daily-12",
    order: 12,
    title: "ประเมินผลการปฏิบัติงาน",
    subtitle: "รอบประเมิน KPI / OKR แบบประเมิน 360 และผลประเมิน",
    icon: "BarChartOutlined",
    items: [
      {
        key: "/admin/appraisal-cycles",
        label: "รอบประเมินผล",
        description: "เปิดหน้า รอบประเมินผล",
        href: "/admin/appraisal-cycles",
        permission: "ems.appraisal_cycles.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/kpi-master",
        label: "KPI / OKR Master",
        description: "เปิดหน้า KPI / OKR Master",
        href: "/admin/kpi-master",
        permission: "ems.kpi_master.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/appraisal-forms",
        label: "แบบฟอร์มประเมิน",
        description: "เปิดหน้า แบบฟอร์มประเมิน",
        href: "/admin/appraisal-forms",
        permission: "ems.appraisal_forms.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/feedback-360",
        label: "360 Feedback",
        description: "เปิดหน้า 360 Feedback",
        href: "/admin/feedback-360",
        permission: "ems.feedback_360.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/appraisal-results",
        label: "ผลประเมิน & Rating",
        description: "เปิดหน้า ผลประเมิน & Rating",
        href: "/admin/appraisal-results",
        permission: "ems.appraisal_results.view",
        icon: "BarChartOutlined",
      },
    ],
  },
  {
    key: "daily-13",
    order: 13,
    title: "Employee Engagement",
    subtitle: "แบบสำรวจความผูกพันและผล eNPS",
    icon: "TeamOutlined",
    items: [
      {
        key: "/admin/engagement-surveys",
        label: "แบบสำรวจความพึงพอใจ",
        description: "เปิดหน้า แบบสำรวจความพึงพอใจ",
        href: "/admin/engagement-surveys",
        permission: "engagement.surveys.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/enps-results",
        label: "ผลสำรวจ eNPS",
        description: "เปิดหน้า ผลสำรวจ eNPS",
        href: "/admin/enps-results",
        permission: "engagement.enps.view",
        icon: "TeamOutlined",
      },
    ],
  },
  {
    key: "daily-14",
    order: 14,
    title: "ข้อร้องเรียน",
    subtitle: "รับเรื่องและติดตามการจัดการข้อร้องเรียน",
    icon: "FileTextOutlined",
    items: [
      {
        key: "/admin/grievances",
        label: "ช่องทางร้องเรียน",
        description: "เปิดหน้า ช่องทางร้องเรียน",
        href: "/admin/grievances",
        permission: "grievance.grievances.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/grievance-cases",
        label: "การจัดการข้อร้องเรียน",
        description: "เปิดหน้า การจัดการข้อร้องเรียน",
        href: "/admin/grievance-cases",
        permission: "grievance.cases.view",
        icon: "FileTextOutlined",
      },
    ],
  },
  {
    key: "daily-15",
    order: 15,
    title: "ฝึกอบรมและพัฒนา",
    subtitle: "หลักสูตร IDP ตารางอบรม ประวัติ ใบรับรอง และงบประมาณ",
    icon: "TeamOutlined",
    items: [
      {
        key: "/admin/training-courses",
        label: "หลักสูตรอบรม",
        description: "เปิดหน้า หลักสูตรอบรม",
        href: "/admin/training-courses",
        permission: "ems.training_courses.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/development-plans",
        label: "แผนพัฒนารายบุคคล (IDP)",
        description: "เปิดหน้า แผนพัฒนารายบุคคล (IDP)",
        href: "/admin/development-plans",
        permission: "ems.development_plans.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/training-schedules",
        label: "ตารางอบรม",
        description: "เปิดหน้า ตารางอบรม",
        href: "/admin/training-schedules",
        permission: "ems.training_schedules.view",
        icon: "CalendarOutlined",
      },
      {
        key: "/admin/training-histories",
        label: "ประวัติการอบรม",
        description: "เปิดหน้า ประวัติการอบรม",
        href: "/admin/training-histories",
        permission: "ems.training_histories.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/certificates",
        label: "ใบรับรอง / วุฒิบัตร",
        description: "เปิดหน้า ใบรับรอง / วุฒิบัตร",
        href: "/admin/certificates",
        permission: "ems.certificates.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/training-budgets",
        label: "งบประมาณอบรม",
        description: "เปิดหน้า งบประมาณอบรม",
        href: "/admin/training-budgets",
        permission: "ems.training_budgets.view",
        icon: "DollarOutlined",
      },
    ],
  },
  {
    key: "daily-16",
    order: 16,
    title: "Employee / Manager Self Service",
    subtitle: "งานบริการตนเองและงานอนุมัติของผู้จัดการ",
    icon: "UserOutlined",
    items: [
      {
        key: "/ess/profile",
        label: "ข้อมูลส่วนตัว (ESS)",
        description: "เปิดหน้า ข้อมูลส่วนตัว (ESS)",
        href: "/ess/profile",
        permission: "ess.profile.view",
        icon: "UserOutlined",
      },
      {
        key: "/ess/payslips",
        label: "สลิปเงินเดือนออนไลน์",
        description: "เปิดหน้า สลิปเงินเดือนออนไลน์",
        href: "/ess/payslips",
        permission: "ess.payslips.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/ess/requests",
        label: "ขอลา / ขอ OT",
        description: "เปิดหน้า ขอลา / ขอ OT",
        href: "/ess/requests",
        permission: "ess.requests.view",
        icon: "UserOutlined",
      },
      {
        key: "/ess/benefits",
        label: "เบิกสวัสดิการ",
        description: "เปิดหน้า เบิกสวัสดิการ",
        href: "/ess/benefits",
        permission: "ess.benefits.view",
        icon: "UserOutlined",
      },
      {
        key: "/mss/approvals",
        label: "อนุมัติคำขอ (MSS)",
        description: "เปิดหน้า อนุมัติคำขอ (MSS)",
        href: "/mss/approvals",
        permission: "mss.approvals.view",
        icon: "CheckCircleOutlined",
      },
      {
        key: "/ess/announcements",
        label: "ประกาศบริษัท",
        description: "เปิดหน้า ประกาศบริษัท",
        href: "/ess/announcements",
        permission: "ess.announcements.view",
        icon: "UserOutlined",
      },
    ],
  },
  {
    key: "daily-17",
    order: 17,
    title: "Offboarding / วินัย",
    subtitle: "ลาออก Exit Interview Clearance วินัย และเลิกจ้าง",
    icon: "FileTextOutlined",
    items: [
      {
        key: "/admin/resignations",
        label: "ใบลาออก",
        description: "เปิดหน้า ใบลาออก",
        href: "/admin/resignations",
        permission: "ems.resignations.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/exit-interviews",
        label: "Exit Interview",
        description: "เปิดหน้า Exit Interview",
        href: "/admin/exit-interviews",
        permission: "ems.exit_interviews.view",
        icon: "AuditOutlined",
      },
      {
        key: "/admin/clearance-checklists",
        label: "Clearance Checklist",
        description: "เปิดหน้า Clearance Checklist",
        href: "/admin/clearance-checklists",
        permission: "ems.clearance_checklists.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/disciplinary-records",
        label: "บันทึกวินัย / ใบเตือน",
        description: "เปิดหน้า บันทึกวินัย / ใบเตือน",
        href: "/admin/disciplinary-records",
        permission: "ems.disciplinary_records.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/terminations",
        label: "การเลิกจ้าง",
        description: "เปิดหน้า การเลิกจ้าง",
        href: "/admin/terminations",
        permission: "ems.terminations.view",
        icon: "FileTextOutlined",
      },
    ],
  },
  {
    key: "daily-18",
    order: 18,
    title: "เอกสารและสัญญา",
    subtitle: "สัญญาจ้าง e-Signature และแฟ้มเอกสารพนักงาน",
    icon: "FileTextOutlined",
    items: [
      {
        key: "/admin/employment-contracts",
        label: "สัญญาจ้าง",
        description: "เปิดหน้า สัญญาจ้าง",
        href: "/admin/employment-contracts",
        permission: "ems.employment_contracts.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/e-signatures",
        label: "e-Signature",
        description: "เปิดหน้า e-Signature",
        href: "/admin/e-signatures",
        permission: "ems.e_signatures.view",
        icon: "FileTextOutlined",
      },
      {
        key: "/admin/personnel-files",
        label: "คลังเอกสารพนักงาน",
        description: "เปิดหน้า คลังเอกสารพนักงาน",
        href: "/admin/personnel-files",
        permission: "ems.personnel_files.view",
        icon: "FileTextOutlined",
      },
    ],
  },
  {
    key: "daily-19",
    order: 19,
    title: "Talent / Succession",
    subtitle: "Succession Plan, Talent Pool และ 9-Box",
    icon: "TeamOutlined",
    items: [
      {
        key: "/admin/succession-plans",
        label: "Succession Plan",
        description: "เปิดหน้า Succession Plan",
        href: "/admin/succession-plans",
        permission: "ems.succession_plans.view",
        icon: "ApartmentOutlined",
      },
      {
        key: "/admin/talent-pools",
        label: "Talent Pool",
        description: "เปิดหน้า Talent Pool",
        href: "/admin/talent-pools",
        permission: "ems.talent_pools.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/nine-box-grid",
        label: "9-Box Grid",
        description: "เปิดหน้า 9-Box Grid",
        href: "/admin/nine-box-grid",
        permission: "ems.nine_box_grid.view",
        icon: "TeamOutlined",
      },
    ],
  },
  {
    key: "daily-20",
    order: 20,
    title: "อัตรากำลังและงบประมาณ",
    subtitle: "Headcount Plan งบบุคลากร และ Turnover",
    icon: "BarChartOutlined",
    items: [
      {
        key: "/admin/headcount-plans",
        label: "แผนอัตรากำลัง (Headcount Plan)",
        description: "เปิดหน้า แผนอัตรากำลัง (Headcount Plan)",
        href: "/admin/headcount-plans",
        permission: "ems.headcount_plans.view",
        icon: "TeamOutlined",
      },
      {
        key: "/admin/workforce-budgets",
        label: "งบประมาณบุคลากร",
        description: "เปิดหน้า งบประมาณบุคลากร",
        href: "/admin/workforce-budgets",
        permission: "ems.workforce_budgets.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/turnover-analysis",
        label: "Turnover Analysis",
        description: "เปิดหน้า Turnover Analysis",
        href: "/admin/turnover-analysis",
        permission: "ems.turnover_analysis.view",
        icon: "BarChartOutlined",
      },
    ],
  },
  {
    key: "daily-21",
    order: 21,
    title: "Workflow / Notification",
    subtitle: "ติดตาม Notification และประวัติการอนุมัติ",
    icon: "CheckCircleOutlined",
    items: [
      {
        key: "/admin/notification-center",
        label: "Notification Center",
        description: "เปิดหน้า Notification Center",
        href: "/admin/notification-center",
        permission: "workflow.notifications.view",
        icon: "CheckCircleOutlined",
      },
      {
        key: "/admin/approval-history",
        label: "Approval History",
        description: "เปิดหน้า Approval History",
        href: "/admin/approval-history",
        permission: "workflow.approval_history.view",
        icon: "CheckCircleOutlined",
      },
    ],
  },
  {
    key: "daily-22",
    order: 22,
    title: "รายงานและวิเคราะห์",
    subtitle: "Dashboard รายงานต้นทุน การลา Compliance และ Custom Report",
    icon: "BarChartOutlined",
    items: [
      {
        key: "/admin/hr-dashboard",
        label: "Dashboard ภาพรวม HR",
        description: "เปิดหน้า Dashboard ภาพรวม HR",
        href: "/admin/hr-dashboard",
        permission: "analytics.hr_dashboard.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/payroll-cost-analysis",
        label: "Payroll Cost Analysis",
        description: "เปิดหน้า Payroll Cost Analysis",
        href: "/admin/payroll-cost-analysis",
        permission: "analytics.payroll_cost.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/leave-ot-reports",
        label: "รายงานการลา / OT",
        description: "เปิดหน้า รายงานการลา / OT",
        href: "/admin/leave-ot-reports",
        permission: "analytics.leave_ot_reports.view",
        icon: "BarChartOutlined",
      },
      {
        key: "/admin/compliance-audit-reports",
        label: "รายงานตรวจสอบ Compliance",
        description: "เปิดหน้า รายงานตรวจสอบ Compliance",
        href: "/admin/compliance-audit-reports",
        permission: "analytics.compliance_audit.view",
        icon: "AuditOutlined",
      },
      {
        key: "/admin/custom-reports",
        label: "Custom Report Builder",
        description: "เปิดหน้า Custom Report Builder",
        href: "/admin/custom-reports",
        permission: "analytics.custom_reports.view",
        icon: "BarChartOutlined",
      },
    ],
  },
  {
    key: "daily-23",
    order: 23,
    title: "ทรัพย์สินและค่าใช้จ่าย",
    subtitle: "ทะเบียนทรัพย์สิน เบิกคืน และค่าใช้จ่าย",
    icon: "BankOutlined",
    items: [
      {
        key: "/admin/asset-register",
        label: "ทะเบียนทรัพย์สิน",
        description: "เปิดหน้า ทะเบียนทรัพย์สิน",
        href: "/admin/asset-register",
        permission: "ems.asset_register.view",
        icon: "BankOutlined",
      },
      {
        key: "/admin/asset-transactions",
        label: "การเบิก-คืนทรัพย์สิน",
        description: "เปิดหน้า การเบิก-คืนทรัพย์สิน",
        href: "/admin/asset-transactions",
        permission: "ems.asset_transactions.view",
        icon: "BankOutlined",
      },
      {
        key: "/admin/expense-claims",
        label: "เบิกค่าใช้จ่าย (Expense Claim)",
        description: "เปิดหน้า เบิกค่าใช้จ่าย (Expense Claim)",
        href: "/admin/expense-claims",
        permission: "ems.expense_claims.view",
        icon: "WalletOutlined",
      },
      {
        key: "/admin/expense-approvals",
        label: "อนุมัติค่าใช้จ่าย",
        description: "เปิดหน้า อนุมัติค่าใช้จ่าย",
        href: "/admin/expense-approvals",
        permission: "ems.expense_approvals.view",
        icon: "CheckCircleOutlined",
      },
    ],
  },
  {
    key: "daily-24",
    order: 24,
    title: "ผู้ใช้งานและสิทธิ์",
    subtitle: "บัญชีผู้ใช้งาน Role/Permission Scope และ Audit",
    icon: "SafetyCertificateOutlined",
    items: [
      {
        key: "/admin/user-accounts",
        label: "ผู้ใช้งานระบบ",
        description: "เปิดหน้า ผู้ใช้งานระบบ",
        href: "/admin/user-accounts",
        permission: "access.user_accounts.view",
        icon: "UserOutlined",
      },
      {
        key: "/admin/roles",
        label: "บทบาทและสิทธิ์",
        description: "เปิดหน้า บทบาทและสิทธิ์",
        href: "/admin/roles",
        permission: "access.roles.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/permissions",
        label: "Permissions",
        description: "เปิดหน้า Permissions",
        href: "/admin/permissions",
        permission: "access.permissions.view",
        icon: "KeyOutlined",
      },
      {
        key: "/admin/user-access-assignments",
        label: "กำหนดบทบาทผู้ใช้งาน",
        description: "กำหนด Role + Scope ให้ผู้ใช้งาน",
        href: "/admin/user-access-assignments",
        permission: "access.user_access_assignments.view",
        icon: "SafetyCertificateOutlined",
      },
      {
        key: "/admin/activity-logs",
        label: "Activity Logs",
        description: "ตรวจสอบประวัติการทำรายการในระบบ",
        href: "/admin/activity-logs",
        permission: "access.activity_logs.view",
        icon: "AuditOutlined",
      },
    ],
  },
  {
    key: "daily-25",
    order: 25,
    title: "API / Integration",
    subtitle: "ตรวจสอบ API Logs และการเชื่อมต่อ",
    icon: "AuditOutlined",
    items: [
      {
        key: "/admin/api-logs",
        label: "API Logs",
        description: "เปิดหน้า API Logs",
        href: "/admin/api-logs",
        permission: "api.api_logs.view",
        icon: "AuditOutlined",
      },
    ],
  },
  {
    key: "daily-26",
    order: 26,
    title: "นำเข้า / ส่งออกข้อมูล",
    subtitle: "Import / Export ข้อมูลเมื่อมีงาน Migration หรือข้อมูลจำนวนมาก",
    icon: "ImportOutlined",
    items: [
      {
        key: "/admin/data-import",
        label: "นำเข้าข้อมูล (Data Import)",
        description: "เปิดหน้า นำเข้าข้อมูล (Data Import)",
        href: "/admin/data-import",
        permission: "data.import.view",
        icon: "ImportOutlined",
      },
      {
        key: "/admin/data-export",
        label: "ส่งออกข้อมูล (Data Export)",
        description: "เปิดหน้า ส่งออกข้อมูล (Data Export)",
        href: "/admin/data-export",
        permission: "data.export.view",
        icon: "ImportOutlined",
      },
    ],
  },
];

export const DASHBOARD_ACTIONS = Object.fromEntries(
  DAILY_WORK_GROUPS
    .flatMap((group) => group.items)
    .map((item) => [item.href, item])
);

/* =========================================================
   งานหลักตาม Role

   ใช้สำหรับ "แนะนำ/จัดลำดับ" เท่านั้น
   รายการงานทั้งหมดด้านล่างยังแสดงตาม Permission เสมอ
========================================================= */

export const ROLE_DAILY_ACTION_KEYS = {
  HR_OFFICER: [
    "/admin/employees",
    "/admin/employee-position-assignments",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/employee-bank-accounts",
    "/admin/applicants",
    "/admin/interviews",
    "/admin/onboarding-checklists",
    "/admin/attendance-records",
    "/admin/leave-requests",
    "/admin/employee-reports",
    "/admin/personnel-files",
  ],
  HR_SUPERVISOR: [
    "/admin/employees",
    "/admin/employee-position-assignments",
    "/admin/org-chart",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/attendance-records",
    "/admin/leave-requests",
    "/admin/interviews",
    "/admin/onboarding-checklists",
    "/admin/employee-reports",
    "/admin/grievance-cases",
  ],
  ASST_HR_MANAGER: [
    "/admin/employees",
    "/admin/employee-position-assignments",
    "/admin/org-chart",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/manpower-requisitions",
    "/admin/interviews",
    "/admin/leave-requests",
    "/admin/employee-reports",
    "/admin/appraisal-results",
    "/admin/headcount-plans",
  ],
  HR_MANAGER: [
    "/admin/employees",
    "/admin/employee-reports",
    "/admin/employee-position-assignments",
    "/admin/org-chart",
    "/admin/manpower-requisitions",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/payroll-periods",
    "/admin/payroll-runs",
    "/admin/leave-requests",
    "/admin/headcount-plans",
    "/admin/turnover-analysis",
  ],
  HR_EXECUTIVE: [
    "/admin/employee-reports",
    "/admin/org-chart",
    "/admin/employee-position-assignments",
    "/admin/headcount-plans",
    "/admin/workforce-budgets",
    "/admin/turnover-analysis",
    "/admin/payroll-cost-analysis",
    "/admin/appraisal-results",
    "/admin/succession-plans",
    "/admin/manpower-requisitions",
  ],
  EMS_ADMIN: [
    "/admin/employees",
    "/admin/employee-position-assignments",
    "/admin/divisional-structures",
    "/admin/org-chart",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/employee-bank-accounts",
    "/admin/data-import",
    "/admin/employee-reports",
    "/admin/user-access-assignments",
    "/admin/activity-logs",
  ],
  EMS_VIEWER: [
    "/admin/employees",
    "/admin/employee-reports",
    "/admin/org-chart",
    "/admin/employee-position-assignments",
  ],
  AUDITOR: [
    "/admin/employee-reports",
    "/admin/activity-logs",
    "/admin/compliance-audit-reports",
    "/admin/benefit-audit-logs",
    "/admin/api-logs",
    "/admin/approval-history",
    "/admin/payroll-cost-analysis",
  ],
  ACCESS_ADMIN: [
    "/admin/user-accounts",
    "/admin/roles",
    "/admin/permissions",
    "/admin/user-access-assignments",
    "/admin/activity-logs",
  ],
  SUPER_ADMIN: [
    "/admin/employees",
    "/admin/employee-position-assignments",
    "/admin/org-chart",
    "/admin/employee-compensations",
    "/admin/employee-statutory-profiles",
    "/admin/employee-bank-accounts",
    "/admin/manpower-requisitions",
    "/admin/interviews",
    "/admin/payroll-periods",
    "/admin/payroll-runs",
    "/admin/data-import",
    "/admin/user-accounts",
    "/admin/user-access-assignments",
    "/admin/activity-logs",
  ],
  MANAGE: [
    "/admin/employees",
    "/admin/org-chart",
    "/admin/employee-position-assignments",
    "/admin/leave-requests",
    "/mss/approvals",
  ],
};

export const DEFAULT_DAILY_ACTION_KEYS = [
  "/admin/employees",
  "/admin/employee-position-assignments",
  "/admin/employee-compensations",
  "/admin/employee-statutory-profiles",
  "/admin/employee-bank-accounts",
  "/admin/employee-reports",
  "/admin/org-chart",
  "/admin/applicants",
  "/admin/interviews",
  "/admin/attendance-records",
  "/admin/leave-requests",
  "/admin/payroll-runs",
  "/admin/user-accounts",
  "/admin/activity-logs",
];

/* =========================================================
   Setup Guide

   ทำครั้งแรก แล้วกลับมาเมื่อ Master / Policy / โครงสร้างเปลี่ยนแปลง
   รายการนี้ตั้งใจครอบคลุมหน้า Setup จาก MenuHRMS เพื่อให้เอา Sidebar ออกได้
========================================================= */

export const SETUP_GUIDE_GROUPS = [
  {
    key: "setup-1",
    order: 1,
    title: "ข้อมูลทั่วไป",
    subtitle: "Master พื้นฐานสำหรับข้อมูลส่วนบุคคล",
    icon: "IdcardOutlined",
    items: [
      { label: "ประเทศ", href: "/admin/countries", permission: "ems.countries.view" },
      { label: "สัญชาติ", href: "/admin/nationalities", permission: "ems.nationalities.view" },
      { label: "คำนำหน้า", href: "/admin/titles", permission: "ems.titles.view" },
      { label: "ศาสนา", href: "/admin/religions", permission: "ems.religions.view" },
      { label: "สถานภาพสมรส", href: "/admin/marital-statuses", permission: "ems.marital_statuses.view" },
      { label: "เพศ", href: "/admin/genders", permission: "ems.genders.view" },
    ],
  },
  {
    key: "setup-2",
    order: 2,
    title: "โครงสร้างองค์กร",
    subtitle: "บริษัท สังกัด แผนก หน่วยงาน และ Position Slot",
    icon: "ApartmentOutlined",
    items: [
      { label: "Position Slot", href: "/admin/org-position-slots", permission: "ems.org_structure.view" },
      { label: "บริษัท", href: "/admin/companies", permission: "ems.companies.view" },
      { label: "กรุ๊ปสังกัด", href: "/admin/branch-groups", permission: "ems.branch_groups.view" },
      { label: "สังกัด", href: "/admin/branches", permission: "ems.branches.view" },
      { label: "แผนก", href: "/admin/departments", permission: "ems.departments.view" },
      { label: "ฝ่าย", href: "/admin/divisions", permission: "ems.divisions.view" },
      { label: "หน่วยงาน", href: "/admin/units", permission: "ems.units.view" },
    ],
  },
  {
    key: "setup-3",
    order: 3,
    title: "Job Architecture",
    subtitle: "สายงาน ระดับ ตำแหน่ง Job และ Salary Band",
    icon: "SolutionOutlined",
    items: [
      { label: "กลุ่มสายงาน", href: "/admin/position-families", permission: "ems.position_families.view" },
      { label: "ระดับของกลุ่มสายงาน", href: "/admin/position-family-levels", permission: "ems.position_family_levels.view" },
      { label: "ระดับตำแหน่ง", href: "/admin/position-levels", permission: "ems.position_levels.view" },
      { label: "ช่วงเงินเดือนตามระดับตำแหน่ง (Salary Band)", href: "/admin/position-level-bands", permission: "ems.position_level_bands.view" },
      { label: "บทบาทงาน / โครงสร้างธุรกิจ", href: "/admin/jobs", permission: "ems.jobs.view" },
      { label: "ตำแหน่ง", href: "/admin/positions", permission: "ems.positions.view" },
      { label: "ตำแหน่งตามหน่วย", href: "/admin/unit-positions", permission: "ems.unit_positions.view" },
      { label: "เส้นทางอาชีพ", href: "/admin/career-paths", permission: "ems.career_paths.view" },
    ],
  },
  {
    key: "setup-4",
    order: 4,
    title: "Skill & Competency Setup",
    subtitle: "Master ทักษะ สมรรถนะ และ Mapping ตามตำแหน่ง",
    icon: "TeamOutlined",
    items: [
      { label: "หมวดหมู่ทักษะ", href: "/admin/skill-categories", permission: "ems.skill_categories.view" },
      { label: "ทักษะทั้งหมด", href: "/admin/skills", permission: "ems.skills.view" },
      { label: "ระดับความเชี่ยวชาญทักษะ", href: "/admin/skill-levels", permission: "ems.skill_levels.view" },
      { label: "ประเภทความสามารถ", href: "/admin/competency-types", permission: "ems.competency_types.view" },
      { label: "Competencies", href: "/admin/competencies", permission: "ems.competencies.view" },
      { label: "ระดับความสามารถ (1-5)", href: "/admin/competency-levels", permission: "ems.competency_levels.view" },
      { label: "กำหนดทักษะตามตำแหน่ง", href: "/admin/position-skills", permission: "ems.position_skills.view" },
      { label: "กำหนดสมรรถนะตามตำแหน่ง", href: "/admin/position-competencies", permission: "ems.position_competencies.view" },
    ],
  },
  {
    key: "setup-5",
    order: 5,
    title: "สวัสดิการ / ประกัน",
    subtitle: "ประเภท แผน และกฎเกณฑ์สวัสดิการ",
    icon: "CheckCircleOutlined",
    items: [
      { label: "ประเภทสวัสดิการ", href: "/admin/benefit-types", permission: "benefits.benefit_types.view" },
      { label: "แผนสวัสดิการ", href: "/admin/benefit-plans", permission: "benefits.benefit_plans.view" },
      { label: "กฎเกณฑ์สวัสดิการ (Policy Rules)", href: "/admin/benefit-policy-rules", permission: "benefits.policy_rules.view" },
    ],
  },
  {
    key: "setup-6",
    order: 6,
    title: "Payroll Setup",
    subtitle: "รอบจ่าย บริษัทเงินเดือน รายการ สูตร และ Salary Structure",
    icon: "DollarOutlined",
    items: [
      { label: "รอบการจ่ายเงิน", href: "/admin/payroll-types", permission: "ems.payroll_types.view" },
      { label: "บริษัทเงินเดือน", href: "/admin/payroll-companies", permission: "ems.payroll_companies.view" },
      { label: "กลุ่มเงินเดือน", href: "/admin/payroll-groups", permission: "ems.payroll_groups.view" },
      { label: "รายการเงินเดือน", href: "/admin/salary-components", permission: "ems.salary_components.view" },
      { label: "ประเภทเงินได้", href: "/admin/earning-types", permission: "ems.earning_types.view" },
      { label: "ประเภทรายการหัก", href: "/admin/deduction-types", permission: "ems.deduction_types.view" },
      { label: "สูตรการคำนวณเงินเดือน", href: "/admin/payroll-formulas", permission: "ems.payroll_formulas.view" },
      { label: "ตัวแปรสูตรคำนวณ", href: "/admin/formula-variables", permission: "ems.formula_variables.view" },
      { label: "โครงสร้างเงินเดือน (Salary Structure)", href: "/admin/salary-structures", permission: "ems.salary_structures.view" },
    ],
  },
  {
    key: "setup-7",
    order: 7,
    title: "ภาษี / ประกันสังคม Setup",
    subtitle: "อัตราภาษี ประกันสังคม และกองทุน",
    icon: "SafetyCertificateOutlined",
    items: [
      { label: "โปรไฟล์ภาษี", href: "/admin/tax-profiles", permission: "ems.tax_profiles.view" },
      { label: "อัตราภาษี", href: "/admin/tax-rates", permission: "ems.tax_rates.view" },
      { label: "ประกันสังคม", href: "/admin/social-security", permission: "ems.social_security.view" },
      { label: "กองทุนสำรองเลี้ยงชีพ", href: "/admin/provident-funds", permission: "ems.provident_funds.view" },
    ],
  },
  {
    key: "setup-8",
    order: 8,
    title: "Insurance Setup",
    subtitle: "ตั้งค่าประกันกลุ่มและประกันสุขภาพ",
    icon: "SettingOutlined",
    items: [
      { label: "ประกันกลุ่ม", href: "/admin/group-insurance", permission: "insurance.group_insurance.view" },
      { label: "ประกันสุขภาพพนักงาน", href: "/admin/health-insurance", permission: "insurance.health_insurance.view" },
    ],
  },
  {
    key: "setup-9",
    order: 9,
    title: "Banking Setup",
    subtitle: "ธนาคารและวิธีการจ่ายเงิน",
    icon: "BankOutlined",
    items: [
      { label: "ธนาคาร", href: "/admin/banks", permission: "ems.banks.view" },
      { label: "วิธีการจ่ายเงิน", href: "/admin/payment-methods", permission: "ems.payment_methods.view" },
    ],
  },
  {
    key: "setup-10",
    order: 10,
    title: "Cost Structure",
    subtitle: "Business Unit, Cost Center, Profit Center และ GL Mapping",
    icon: "DollarOutlined",
    items: [
      { label: "Business Unit", href: "/admin/business-units", permission: "ems.business_units.view" },
      { label: "Cost Center", href: "/admin/cost-centers", permission: "ems.cost_centers.view" },
      { label: "Profit Center", href: "/admin/profit-centers", permission: "ems.profit_centers.view" },
      { label: "GL Mapping", href: "/admin/gl-mappings", permission: "ems.gl_mappings.view" },
    ],
  },
  {
    key: "setup-11",
    order: 11,
    title: "Employee Master Setup",
    subtitle: "ประเภทการจ้าง สถานะ และการสร้างรหัสพนักงาน",
    icon: "IdcardOutlined",
    items: [
      { label: "ประเภทการจ้าง", href: "/admin/employment-types", permission: "ems.employment_types.view" },
      { label: "สถานะพนักงาน", href: "/admin/employee-statuses", permission: "ems.employee_statuses.view" },
      { label: "ตั้งค่ารหัสพนักงาน", href: "/admin/employee-code-settings", permission: "ems.employee_code_settings.view" },
      { label: "เลขรันรหัสพนักงาน", href: "/admin/employee-running", permission: "ems.employee_running.view" },
    ],
  },
  {
    key: "setup-12",
    order: 12,
    title: "เวลา / ลา Setup",
    subtitle: "กะ กฎ OT ประเภทลา และปฏิทินวันหยุด",
    icon: "ClockCircleOutlined",
    items: [
      { label: "กะการทำงาน", href: "/admin/work-shifts", permission: "ems.work_shifts.view" },
      { label: "คำนวณล่วงเวลา (OT)", href: "/admin/overtime-rules", permission: "ems.overtime_rules.view" },
      { label: "ประเภทวันลา", href: "/admin/leave-types", permission: "ems.leave_types.view" },
      { label: "ปฏิทินวันหยุด", href: "/admin/holiday-calendars", permission: "ems.holiday_calendars.view" },
    ],
  },
  {
    key: "setup-13",
    order: 13,
    title: "Workflow Setup",
    subtitle: "ตั้งค่า Workflow Builder",
    icon: "CheckCircleOutlined",
    items: [
      { label: "Workflow Builder", href: "/admin/workflow-builder", permission: "workflow.builder.view" },
    ],
  },
  {
    key: "setup-14",
    order: 14,
    title: "User Access Setup",
    subtitle: "Role และ Permission ของระบบ",
    icon: "SafetyCertificateOutlined",
    items: [
      { label: "บทบาทและสิทธิ์", href: "/admin/roles", permission: "access.roles.view" },
      { label: "Permissions", href: "/admin/permissions", permission: "access.permissions.view" },
    ],
  },
  {
    key: "setup-15",
    order: 15,
    title: "API Setup",
    subtitle: "API Client และ Token",
    icon: "AuditOutlined",
    items: [
      { label: "API Clients", href: "/admin/api-clients", permission: "api.api_clients.view" },
      { label: "API Tokens", href: "/admin/api-tokens", permission: "api.api_tokens.view" },
    ],
  },
  {
    key: "setup-16",
    order: 16,
    title: "System Settings",
    subtitle: "ค่าระบบ ปีงบประมาณ และสกุลเงิน",
    icon: "ImportOutlined",
    items: [
      { label: "ตั้งค่าทั่วไป", href: "/admin/system-settings", permission: "system.settings.view" },
      { label: "ตั้งค่าปีงบประมาณ (Fiscal Year)", href: "/admin/fiscal-years", permission: "system.fiscal_years.view" },
      { label: "ตั้งค่าสกุลเงิน (Currency)", href: "/admin/currencies", permission: "system.currencies.view" },
    ],
  },
];
