import {
  TeamOutlined,
  GiftOutlined,
  DollarOutlined,
  ClockCircleOutlined,
  ToolOutlined,
  FileTextOutlined,
} from "@ant-design/icons";

export const systemApps = [
  {
    code: "EMS",
    title: "Employee Master",
    subtitle: "ระบบข้อมูลพนักงาน",
    description: "จัดการข้อมูลพนักงาน โครงสร้างองค์กร และสิทธิ์ผู้ใช้งาน",
    path: "/admin/dashboard",
    permission: "ems.portal.view",
    icon: <TeamOutlined />,
    badge: "Core",
    category: "HR Core",
    sortOrder: 1,
    gradient: "from-sky-500 to-blue-600",
  },

  {
    code: "BENEFIT",
    title: "Benefit",
    subtitle: "ระบบสวัสดิการ",
    description: "เบิกสิทธิ์ ตรวจสอบสิทธิ์ และอนุมัติสวัสดิการ",
    path: "/benefit",
    permission: "benefit.view",
    icon: <GiftOutlined />,
    badge: "Service",
    category: "Employee Service",
    sortOrder: 2,
    gradient: "from-emerald-500 to-green-600",
  },

  {
    code: "HRM",
    title: "HRM",
    subtitle: "ระบบบริหารงาน HR",
    description: "ลางาน เวลาทำงาน คำร้อง และงานบุคคล",
    path: "/hrm",
    permission: "hrm.view",
    icon: <ClockCircleOutlined />,
    badge: "HR",
    category: "HR Core",
    sortOrder: 3,
    gradient: "from-violet-500 to-purple-600",
  },

  {
    code: "PAYROLL",
    title: "Payroll",
    subtitle: "ระบบเงินเดือน",
    description: "เงินเดือน รายได้ รายหัก และรายงานเงินเดือน",
    path: "/payroll",
    permission: "payroll.view",
    icon: <DollarOutlined />,
    badge: "Private",
    category: "Finance",
    sortOrder: 4,
    gradient: "from-orange-500 to-red-500",
  },

  {
    code: "RECRUITMENT",
    title: "Recruitment",
    subtitle: "ระบบสรรหาพนักงาน",
    description: "ตำแหน่งว่าง ผู้สมัคร นัดสัมภาษณ์ และผลการคัดเลือก",
    path: "/recruitment",
    permission: "recruitment.view",
    icon: <FileTextOutlined />,
    badge: "Hiring",
    category: "HR Core",
    sortOrder: 5,
    gradient: "from-cyan-500 to-sky-600",
  },

  {
    code: "ASSET",
    title: "Asset",
    subtitle: "ระบบทรัพย์สิน",
    description: "จัดการอุปกรณ์ ทรัพย์สิน และการเบิกคืนอุปกรณ์",
    path: "/asset",
    permission: "asset.view",
    icon: <ToolOutlined />,
    badge: "Operation",
    category: "Operation",
    sortOrder: 6,
    gradient: "from-slate-500 to-slate-700",
  },

  {
    code: "LEAVE",
    title: "Leave System",
    subtitle: "ระบบลางาน",
    description: "ยื่นคำขอลา ตรวจสอบสิทธิ์ และอนุมัติการลา",
    path: "/leave",
    hardNav: true,             
    permission: "leave.view",
    icon: <ClockCircleOutlined />,
    badge: "Leave",
    category: "HR Core",
    sortOrder: 4,
    gradient: "from-teal-500 to-cyan-600",
  },
];